spring.application.name=mansion

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ghostmansion
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=e443e272b5941531eb74ea76de9531114a6ae2dee0d6715dee2a88b4949e9d0338b0de091796b5270e2aac373a1c5cd50338c5654cbcd74aedc6a61ea4bb9322a9
#3600000 = 1h
jwt.expirationMs=36000000

logging.level.org.springframework.security=DEBUG

# File uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
